// src/constants/authorOptions.ts
export const authorOptions: string[] = [
    "Presidente Nacional",
    "Vice Presidente para Assuntos Externos",
    "Vice Presidente para Assuntos Internos",
    "Secretário(a) Geral",
    "Diretor Financeiro Interno",
    "Diretor Financeiro Externo",
    "Diretor Nacional de Comunicação e Marketing",
    "Diretor Nacional de Capacity Building",
    "Diretor Nacional de Educação Médica",
    "Diretor Nacional de Saúde Pública",
    "Diretor Nacional de Direitos Humanos e Paz",
    "Diretor Nacional de Direitos Sexuais e Reprodutivos",
    "Diretor Nacional de Intercâmbio Nacional para Assuntos Internos",
    "Diretor Nacional de Intercâmbio Nacional para Assuntos Externos",
    "Diretor Nacional de Intercâmbio Internacional Clínico-Cirúrgico para Incomings",
    "Diretor Nacional de Intercâmbio Internacional Clínico-Cirúrgico para Outgoings",
    "Diretor Nacional de Intercâmbio Internacional de Pesquisa para Incomings",
    "Diretor Nacional de Intercâmbio Internacional de Pesquisa para Outgoings",
    "Diretor Nacional de Programas e Atividades",
    "Diretor Nacional de Publicação, Pesquisa e Extensão",
    "Diretor Nacional de Alumni",
    "Yellow Team",
    "Divisão de Relações Públicas",
    "Red Light Team",
    "Green Lamp Team",
    "White Team",
    "Coordenadores Nacionais de Programas",
    "Scientific Team",
    "Capacity Building Team",
    "Comissão de Reforma e Elaboração de Documentos",
    "National Exchange Team",
    "Time de Intercâmbios Nacionais",
    "NSSB",
    "Outros",
];
