export const allowedTimes = [
    { href: "tre", label: "Time de Relações Externas", css: "bg-amber-600 text-black" },
    { href: "drp", label: "Divisão de Relações Públicas", css: "bg-pink-400 text-white" },
    { href: "cbt", label: "Capacity Building Team", css: "bg-stone-950 text-white" },
    { href: "st", label: "Scientific Team", css: "bg-gray-400 text-black" },
    { href: "net", label: "National Exchange Team", css: "bg-sky-600 text-white" },
    { href: "nssb", label: "National SCORE Supervising Board", css: "bg-blue-600 text-white" },
    { href: "tin", label: "Time de Intercâmbio Nacional", css: "bg-gradient-to-r from-yellow-300 via-green-500 to-blue-600 text-black" },
    { href: "ot", label: "Orange Team", css: "bg-orange-500 text-white" },
    { href: "rlt", label: "Redlight Team", css: "bg-red-600 text-white" },
    { href: "glt", label: "Green Lamp Team", css: "bg-green-600 text-white" },
    { href: "wt", label: "White Team", css: "bg-gray-50 text-black" },
    { href: "yt", label: "Yellow Team", css: "bg-yellow-400 text-black" },
    { href: "cnp", label: "Coordenadores Nacionais de Programas" },
];
